# Generated by Django 4.2.14 on 2024-10-14 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('blog_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=400)),
                ('private', models.BooleanField(default=False)),
                ('data_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
